- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Add Jenkins key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins home directory exists
  file:
    path: "{{ jenkins_home }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Configure Jenkins environment
  copy:
    dest: /etc/default/jenkins
    content: |
      JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      JENKINS_HOME={{ jenkins_home }}
      JENKINS_PORT={{ jenkins_port }}
  become: yes
  notify: restart jenkins

- name: Set JAVA_HOME in Jenkins systemd service
  lineinfile:
    path: /lib/systemd/system/jenkins.service
    regexp: '^#?Environment="JAVA_HOME=.*"'
    line: 'Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"'
    backrefs: yes
  become: yes
  notify: restart jenkins
