---

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present

- name: Ensure Java 17 is set as default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java

- name: Add Jenkins repository key
  apt_key:
    url: "{{ jenkins_key_url }}"
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Ensure Jenkins service is started and enabled
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start up
  wait_for:
    port: "{{ jenkins_port }}"
    delay: "{{ jenkins_startup_delay }}"
    timeout: "{{ jenkins_startup_timeout }}"

- name: Get Jenkins initial admin password
  command: "cat {{ jenkins_home }}/secrets/initialAdminPassword"
  register: jenkins_initial_password
  changed_when: false

- name: Display Jenkins initial admin password
  debug:
    var: jenkins_initial_password.stdout

