---
# Common role: update system and install basic packages
- name: Update all packages
  apt:
    name: "*"
    state: latest

- name: Install required tools
  apt:
    name:
      - git
      - curl
      - wget
      - unzip
    state: present
    update_cache: yes

- name: Download AWS CLI v2 installer
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unzip AWS CLI installer
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI v2
  command: /tmp/aws/install

- name: Verify aws version
  command: aws --version

